functionality:
  name: check_samplesheet
  namespace: qc
  description: |
    Check whether sample sheets are in the correct format.
  usage: check_samplesheet --input sample_sheet.csv
  arguments:
    - name: --input
      type: file
      required: true
      multiple: true
      description: One or more sample sheets.
      example: sample_sheet.csv
  resources:
    - type: python_script
      path: script.py
  tests:
    - type: python_script
      path: test.py
    - path: ../../../resources_test/bs_195891710
platforms:
  - type: docker
    image: python:3.9