functionality:
  name: loompy
  namespace: rna_velocity
  description: Uknown
  usage: |
    python script.py \
      --input /path/to/bcl \
      --sample_sheet sample_sheet.csv \
      --output fastqs
  arguments:
    - type: file
      name: --input
      description: Path to the .fastq.gz files to align and perform RNA velocity on.
      example: /path/to/fastqs
      required: true
    - type: file
      name: --reference_genome
      description: The path to the reference genome.
      required: true
    - type: file
      name: --metadata
      description: The path to the metadata file.
      required: true

    - type: string
      name: --partition_id
      description: The index of the sample group.
    - type: integer
      name: --num_partitions
      description: The number of partitions
      default: 10
    - type: integer
      name: --cell_count
      description: The number of cells. 
      default: 3000

    - type: file
      name: --output
      direction: output
      description: The folder to store the results in
      example: "/path/to/output"
      required: true
  resources:
    - type: python_script
      path: script.py
  tests:
    - type: python_script
      path: test.py
    - path: ../../../resources_test/bs_195891710
platforms:
  - type: docker
    image: ghcr.io/data-intuitive/cellranger:6.1
  - type: native