functionality:
  name: "download_basespace"
  namespace: "download"
  description: |
    Download a BCL file/folder from basespace.
  usage: |
    download_basespace --id 195891710 --output output_dir/
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--id"
      type: string
      description: "An ID of entity"
      required: true
      example: "195891710"
    - name: "--output"
      type: file
      example: path_to_dir/
      required: true
      direction: output
      description: "Path where to store BCL output."
    - name: "--verbose"
      alternatives: ["-v"]
      type: boolean_true
      description: Increase verbosity
    - name: "--compress"
      type: boolean_true
      description: Write gzipped tar archive.
    - name: "--overwrite"
      type: boolean_true
      description: Overwrite files that already exist and have the same file size
    - name: "--extension"
      type: string
      description: List of extensions to filter by
      multiple: true
      example: xml:txt
    - name: "--api_server"
      type: string
      description: BaseSpace API hostname
      default: "https://api.basespace.illumina.com"
    - name: "--access_token"
      type: string
      description: Manual BaseSpace API access token
      default: "610b74406284445fa38691d551c30e4a"
  resources:
    - type: bash_script
      path: script.sh
  tests:
    - type: bash_script
      path: run_test.sh
platforms:
  - type: docker
    image: "ubuntu:22.04"
    setup:
      - type: apt
        packages: [ wget ]
      - type: docker
        run: 
          - wget "https://launch.basespace.illumina.com/CLI/latest/amd64-linux/bs" -O /usr/bin/bs && chmod +x /usr/bin/bs
  - type: nextflow
    variant: vdsl3
