functionality:
  name: cellranger_count
  namespace: alignment
  description: Run alignment jobs using 10x
  arguments:
    # inputs
    - type: file
      name: --input
      required: true
      description: The folder with fastq.gz files to align.
    - type: file
      name: --transcriptome
      required: true
      description: The path to reference tar.gz file.
    
    # outputs
    - type: file
      name: --output
      direction: output
      required: true
      description: The folder to store the alignment results.
    # TODO: implement split component for splitting output into a tuple of files.

    # arguments
    - type: integer
      name: --expect_cells
      default: 3000
      description: "Expected number of recovered cells, used as input to cell calling algorithm."

    # - type: integer
    #   name: --num_partitions
    #   required: true
    #   default: 10
    #   description: |
    #     Number of groups to divide samples
    #     into for the alignment run. Enter 10 as the default
    #     value here since we don't divide a single sample
    # - type: integer
    #   name: --partition_id
    #   required: true
    #   default: 10
    #   description: |
    #     Index of sample group. Enter 0 as the default value here 
    #     since we only have one sample.

    # runtime args
    - type: integer
      name: --cores
      description:  Set max cores the pipeline may request at one time.
    - type: integer
      name: --memory
      description: Set max GB the pipeline may request at one time.
  resources:
    - type: bash_script
      path: script.sh
  tests:
    - type: python_script
      path: test.py
    - path: ../../../resources_test/pbmc_1k_protein_v3
    - path: ../../../resources_test/reference/refdata-gex-GRCh38-2020-A
platforms:
  - type: docker
    image: ghcr.io/data-intuitive/cellranger:6.1