functionality:
  name: cellranger_count
  namespace: alignment
  description: Run alignment jobs using 10x
  arguments:
    - type: file
      name: --input_path
      required: true
      description: The folder with fastq.gz files to align.
    - type: file
      name: --transcriptome
      required: true
      description: The folder with fastq.gz files to align.
    - type: file
      name: --output_path
      direction: output
      required: true
      description: The folder to store the alignment results.
    # - type: integer
    #   name: --num_partitions
    #   required: true
    #   default: 10
    #   description: |
    #     Number of groups to divide samples
    #     into for the alignment run. Enter 10 as the default
    #     value here since we don't divide a single sample
    # - type: integer
    #   name: --partition_id
    #   required: true
    #   default: 10
    #   description: |
    #     Index of sample group. Enter 0 as the default value here 
    #     since we only have one sample.
    - type: integer
      name: --cores
      description:  Set max cores the pipeline may request at one time.
    - type: integer
      name: --memory
      description: Set max GB the pipeline may request at one time.
  resources:
    - type: bash_script
      path: script.sh
platforms:
  - type: docker
    image: ghcr.io/data-intuitive/cellranger:6.1