functionality:
  name: cellranger_arc_aggr
  namespace: multiomics
  description: Aggregate
  usage: |
    bcl2fastq --input /path/to/bcl --sample_sheet \
      sample_sheet.csv --output fastqs --reports reports
  arguments:
    - type: file
      name: --data
      description: Path to the data
      example: /path/to/data
      required: true
    - type: file
      name: --reference_genome
      description: Path to the reference genome
      example: /path/to/reference_genome
      required: true
    - type: file
      name: --output
      description: Path to the output directory
      example: /path/to/directory
      required: true
    - type: string
      name: --run_id
      description: The run ID
      required: true

    - type: file
      name: --peaks
      description: Path to the bed file to use for peak calling
      example: /path/to/bed
    - type: boolean
      name: --neurips
      description: Unknown
      default: false

  resources:
    - type: python_script
      path: script.py
  tests:
    - type: python_script
      path: test.py
    - path: ../../../resources_test/bs_195891710
platforms:
  - type: docker
    image: ghcr.io/data-intuitive/cellranger:6.1
    setup:
    - type: conda
      packages: [numpy, pandas, numpy]
  - type: native