functionality:
  name: bcl2fastq
  namespace: demux
  description: Demultiplex raw sequencing data
  usage: |
    bcl2fastq --input /path/to/bcl --sample_sheet \
      sample_sheet.csv --output fastqs --reports reports
  arguments:
    - type: file
      name: --input
      description: Path to the untarred BCL files.
      example: /path/to/bcl
      required: true
    - type: file
      name: --sample_sheet
      description: The path to the sample sheet.
      example: SampleSheet.csv
    - type: file
      name: --output
      direction: output
      description: The folder to store the demux results
      example: "/path/to/output"
      required: true
    - type: boolean_true
      name: --star_structure
      description: Group the fastq files into folders based on sample name
    - type: boolean_true
      name: --skip_undetermined
      description: Don't upload the Undetermined files (can save time)
    # - type: string
    #   name: --bcl2fastq_options
    #   description: Options to pass to bcl2fastq
    #   multiple_sep: ","
  resources:
    - type: python_script
      path: script.py
  tests:
    - type: python_script
      path: test.py
    - path: ../../../resources_test/bs_195891710
platforms:
  - type: docker
    image: ghcr.io/data-intuitive/cellranger:6.1
    setup:
      - type: yum
        packages:
          - python3
      - type: docker
        run: 
          - ln -fs /usr/bin/python3 /usr/bin/python
  - type: native