functionality:
  name: convert_10x_h5_to_h5ad
  namespace: convert
  arguments:
    - name: --input
      type: file
      required: true
      example: filtered_feature_bc_matrix.h5
      description: Output h5 from a Cell Ranger count run.
    - name: --output
      type: file
      direction: output
      required: true
      description: Counts in AnnData format.
      example: output.h5ad
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: python:3.9
    setup:
      - type: python
        pip: scanpy
  - type: nextflow